### ISSUE TITLE
Is it possible that the output causal graph is not a DAG?

### ISSUE THREAD

**Issue by zmlin1998** [jarrycyx/UNN#2]
May I sask if it is possible that the output is not a DAG? 
If that is the case, how can we handle it or can we consider it as a causal graph? 
Thanks!

**Comment by jarrycyx** [comment]
Really sorry about the confusion about DAG in the original paper.

Our idea is that, Granger causal graphs in time-series are naturally DAG, since causality does not flow backwards in time dimension. The groundtruth summary graphs (and the discovered CPGs) are not DAGs because we omit the time dimension.

Anyway, thanks for your question.

**Comment by jarrycyx** [comment]
This point of view is consistent with the works of PCMCI and Neural Granger Causality. However, it does remain a controversial problem if the discovered summary graphs count as causal graphs.

We reopen this issue for possible further discussion.
